hw6
================

### Problem 1:

To obtain a distribution for $\hat{r}^2$, we’ll follow basically the
same procedure we used for regression coefficients: draw bootstrap
samples; the a model to each; extract the value I’m concerned with; and
summarize. Here, we’ll use `modelr::bootstrap` to draw the samples and
`broom::glance` to produce `r.squared` values.

``` r
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

``` r
weather_df %>% 
  modelr::bootstrap(n = 1000) %>% 
  mutate(
    models = map(strap, ~lm(tmax ~ tmin, data = .x) ),
    results = map(models, broom::glance)) %>% 
  select(-strap, -models) %>% 
  unnest(results) %>% 
  ggplot(aes(x = r.squared)) + geom_density()
```

<img src="p8105_hw6_rp3022_files/figure-gfm/unnamed-chunk-1-1.png" width="90%" />

In this example, the $\hat{r}^2$ value is high, and the upper bound at 1
may be a cause for the generally skewed shape of the distribution. If we
wanted to construct a confidence interval for $R^2$, we could take the
2.5% and 97.5% quantiles of the estimates across bootstrap samples.
However, because the shape isn’t symmetric, using the mean +/- 1.96
times the standard error probably wouldn’t work well.

We can produce a distribution for $\log(\beta_0 * \beta1)$ using a
similar approach, with a bit more wrangling before we make our plot.

``` r
weather_df %>% 
  modelr::bootstrap(n = 1000) %>% 
  mutate(
    models = map(strap, ~lm(tmax ~ tmin, data = .x) ),
    results = map(models, broom::tidy)) %>% 
  select(-strap, -models) %>% 
  unnest(results) %>% 
  select(id = `.id`, term, estimate) %>% 
  pivot_wider(
    names_from = term, 
    values_from = estimate) %>% 
  rename(beta0 = `(Intercept)`, beta1 = tmin) %>% 
  mutate(log_b0b1 = log(beta0 * beta1)) %>% 
  ggplot(aes(x = log_b0b1)) + geom_density()
```

<img src="p8105_hw6_rp3022_files/figure-gfm/unnamed-chunk-2-1.png" width="90%" />

As with $r^2$, this distribution is somewhat skewed and has some
outliers.

The point of this is not to say you should always use the bootstrap –
it’s possible to establish “large sample” distributions for strange
parameters / values / summaries in a lot of cases, and those are great
to have. But it is helpful to know that there’s a way to do inference
even in tough cases.

### Problem 2:

Importing the raw homicides dataset:

``` r
library (readr)

urlfile="https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv"

homicide_raw <-read_csv(url(urlfile)) %>% 
  janitor::clean_names()
```

``` r
homicide = homicide_raw %>%
unite('city_state',"city":"state", remove = FALSE)%>%
  select(-city,-state)%>%
   mutate (resolved = case_when (disposition == "Closed without arrest" ~ "unresolved", 
                                  disposition == "Open/No arrest" ~ "unresolved", 
                                  disposition == "Closed by arrest" ~ "resolved"),
           resolved = as.factor(resolved),
           resolved = fct_relevel(resolved, "unresolved"),
           victim_age = as.numeric(victim_age)) %>%
    filter(!(city_state %in% c("Dallas_TX" , "Phoenix_AZ","Kansas City_MO",  "Tulsa_AL"))) %>% 
     filter(victim_race == "White" | victim_race == "Black")
```

``` r
baltimore = homicide %>%
  filter(city_state == "Baltimore_MD")

balt_OR = baltimore %>% 
  glm(resolved ~ victim_age+victim_race+victim_sex, data = ., family=binomial()) %>% 
  broom::tidy() %>% 
  mutate(OR = exp(estimate),
         L_95CI = exp(estimate - (1.96*std.error)),
         U_95CI = exp(estimate +(1.96*std.error))) %>% 
  filter(term== "victim_sexMale") %>% 
  select(OR, L_95CI, U_95CI)

knitr::kable(balt_OR)
```

|        OR |   L_95CI |    U_95CI |
|----------:|---------:|----------:|
| 0.4255117 | 0.324559 | 0.5578655 |

The estimate of the adjusted odds ratio for solving homicides comparing
male victims to female victims keeping all other variables fixed are
0.43 with a 95% CI (0.32, 0.56)

``` r
OR_city = homicide%>% 
  nest(data = -city_state) %>% 
  mutate(model_city = map(data, ~ glm(resolved ~ victim_age + victim_sex + victim_race, 
                                 data = ., family = "binomial")), 
         result = map(model_city, broom::tidy)) %>% 
  select(-data, -model_city) %>% 
  unnest(result) %>% 
  mutate(OR = exp(estimate),
         L_95ci = exp(estimate - 1.96*std.error),
         U_95ci = exp(estimate + 1.96*std.error)) %>% 
  filter(term == "victim_sexMale") %>% 
  select(city_state, OR, L_95ci, U_95ci)
```

``` r
plot_city = OR_city %>% 
  mutate(city_state = fct_reorder(city_state, OR)) %>% 
  ggplot(aes(x = city_state, y = OR, colour = OR)) + 
  geom_point() + 
  geom_errorbar(aes(ymin = L_95ci, ymax = U_95ci, width = .3)) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1), 
        legend.position = "none") + 
  labs(
    x = "City",
    y = "Estimated odds ratio",
    title = " Adjusted odds of solving homicides compaing male vs female victim across major U.S. cities, 2007-2017",
    caption = paste0(
          "Error bars represent the 95% confidence interval.",
          "\nSource: The Washington Post."))
plot_city
```

<img src="p8105_hw6_rp3022_files/figure-gfm/unnamed-chunk-7-1.png" width="90%" />

Based on the graph, it can be noted that across most cities the ORs are
less than 1. This suggests that there are decreased odds of resolving a
homicide when the victim is male vs. when the victim is female. This
odds are lowest for New York. For many cities the 95% CI fo the adjusted
OR crosses the null value of , which denotes a statistically
insignificant association between sex and solving homicides.The only
cities which have increased odds of solving a homicide when the victim
is male vs. when the victim is female are Albequerque, Stockton and
Fresno but their 95% CI crosses the null value of 1.

### Problem 3

``` r
birthweight = read_csv("./data/birthweight.csv") %>%
  janitor::clean_names() %>% 
  mutate(bwt = bwt/453.59) %>% 
    mutate(
   babysex = recode(babysex, `1` = "male", `2` = "female"),
    babysex = factor(babysex)
)
```

For tidying the dataset, I converted birthweight of the baby from grams
to pounds to maintain consistency in measuring weight between variables
bwt (birthweight of baby) and delwt (mother’s weight at delivery). I
also converted babysex to a factor variable.

Proposing my own model: First I included variables associated with the
baby that I think are helpful in predicting baby’s weight

``` r
my_model_1 = lm(bwt~ babysex +bhead+blength+gaweeks, data=birthweight)
 summary(my_model_1)
```

    ## 
    ## Call:
    ## lm(formula = bwt ~ babysex + bhead + blength + gaweeks, data = birthweight)
    ## 
    ## Residuals:
    ##     Min      1Q  Median      3Q     Max 
    ## -2.4712 -0.4200 -0.0273  0.3921  5.7614 
    ## 
    ## Coefficients:
    ##               Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept) -13.736490   0.213086 -64.465  < 2e-16 ***
    ## babysexmale  -0.073678   0.019488  -3.781 0.000158 ***
    ## bhead         0.310561   0.007861  39.508  < 2e-16 ***
    ## blength       0.180241   0.004588  39.287  < 2e-16 ***
    ## gaweeks       0.031013   0.003336   9.297  < 2e-16 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 0.6299 on 4337 degrees of freedom
    ## Multiple R-squared:  0.6891, Adjusted R-squared:  0.6888 
    ## F-statistic:  2403 on 4 and 4337 DF,  p-value: < 2.2e-16

After comparing the estimates, it can be observed that the p value of
all variables is \< .05 and is significant. Moreover the $r^2$ value is
0.6891 indicating that 68.91% of variance in the birthweight can be
explained by variability in the selected variables.

I also want to add variables associated with the baby’s parents that I
think are important in predicting baby’s weight

``` r
my_model_2 = lm(bwt~ babysex +bhead+blength+gaweeks+delwt+smoken+fincome, data=birthweight)
summary(my_model_2)
```

    ## 
    ## Call:
    ## lm(formula = bwt ~ babysex + bhead + blength + gaweeks + delwt + 
    ##     smoken + fincome, data = birthweight)
    ## 
    ## Residuals:
    ##     Min      1Q  Median      3Q     Max 
    ## -2.6374 -0.4048 -0.0181  0.3935  5.5808 
    ## 
    ## Coefficients:
    ##               Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept) -1.371e+01  2.101e-01 -65.236  < 2e-16 ***
    ## babysexmale -6.777e-02  1.913e-02  -3.542 0.000401 ***
    ## bhead        2.984e-01  7.763e-03  38.433  < 2e-16 ***
    ## blength      1.737e-01  4.538e-03  38.281  < 2e-16 ***
    ## gaweeks      2.947e-02  3.287e-03   8.965  < 2e-16 ***
    ## delwt        4.569e-03  4.367e-04  10.463  < 2e-16 ***
    ## smoken      -5.564e-03  1.280e-03  -4.348 1.41e-05 ***
    ## fincome      2.766e-03  3.654e-04   7.569 4.56e-14 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 0.6176 on 4334 degrees of freedom
    ## Multiple R-squared:  0.7013, Adjusted R-squared:  0.7008 
    ## F-statistic:  1453 on 7 and 4334 DF,  p-value: < 2.2e-16

It can be seen in the summary of the 2nd model that the p value of all
variables \> 0.05 and is significant. Moreover there is an increase the
$r^2$ value of the model i.e 0.7013 Thus I am keeping this as my
selected final model
